# Generated by Django 4.0.8 on 2022-12-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.TextField(),
        ),
    ]
