# Generated by Django 4.0.8 on 2022-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
