# Generated by Django 4.0.8 on 2022-12-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_proposalexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworkitem',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upworkitem',
            name='posted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
