# Generated by Django 4.0.8 on 2023-01-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_myproposal_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproposal',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
